#!/usr/bin/env bash
# Stand up the local MediaWiki this project writes to.
#
# `AGENTS.md` §2 forbids writing to a real wiki, so the agent needs one of its own. This builds
# it natively rather than in a container: containers are a packaging concern and this stack is
# new to the project, so the first version is the one that is easiest to debug. Moving it into
# Docker is a separate, later task (`summary.md` §10).
#
# Idempotent. Re-running skips the download and refuses to re-install over an existing wiki.
#
#   ./scripts/setup_wiki.sh          # install
#   ./scripts/seed_wiki.py           # then load the 12 pages from snapshots/seed/
#
# Everything it generates is a secret or a build artifact: credentials go to `.env`, the
# MediaWiki tree to `wiki/`. Both are gitignored. The only version-controlled output is
# `wiki-config/LocalSettings.overrides.php`, which is where our actual decisions live.
set -euo pipefail

# 1.43 is the LTS *and* the version the MCU Wiki itself runs, per snapshots/manifest.json —
# so the demo instance and the wiki it mirrors answer with the same generator string.
MW_VERSION="${MW_VERSION:-1.43.9}"
MW_SERIES="${MW_VERSION%.*}"
PORT="${MEDIAWIKI_PORT:-8080}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WIKI="$ROOT/wiki"
ENV_FILE="$ROOT/.env"

for tool in php mariadb curl; do
	command -v "$tool" >/dev/null || { echo "missing: $tool (brew install mariadb php)"; exit 1; }
done

# Homebrew's MariaDB authenticates root over unix_socket, so `-u root` is refused even with the
# right password. The installing OS user is granted instead — connect as them and say nothing
# about root.
mariadb -e 'SELECT 1' >/dev/null 2>&1 || {
	echo "cannot reach MariaDB. Start it with: brew services start mariadb"; exit 1; }

if [ -f "$WIKI/LocalSettings.php" ]; then
	echo "wiki/ already installed — delete it to start over. Seeding is safe to re-run."
	exit 0
fi

# --- credentials -------------------------------------------------------------------------
# Generated once and written to .env, which is the only place a value may live (`AGENTS.md` §2).
# Names are overridable, values never are. `AGENTS.md` §2 keeps deployment identifiers in
# `.env`, and a deployed instance should not have to edit a committed file to pick its own —
# so these are defaults for a localhost install, and the environment wins.
DB_NAME="${MEDIAWIKI_DB_NAME:-continuity_wiki}"
DB_USER="${MEDIAWIKI_DB_USER:-wikiuser}"
DB_PASS="$(openssl rand -hex 16)"
# The wiki is treated as external even though it is ours (`AGENTS.md` §2), so the agent needs a
# credential to read it. Generated here so nobody has to invent one by hand.
API_KEY="$(openssl rand -hex 24)"
ADMIN_USER="${MEDIAWIKI_ADMIN_USER:-ContinuityAdmin}"
ADMIN_PASS="$(openssl rand -hex 16)"
BOT_NAME="${MEDIAWIKI_BOT_NAME:-ContinuityBot}"
BOT_APPID="${MEDIAWIKI_BOT_APPID:-seeder}"

echo "==> database"
mariadb <<SQL
CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';
FLUSH PRIVILEGES;
SQL

echo "==> mediawiki $MW_VERSION"
mkdir -p "$WIKI"
TARBALL="/tmp/mediawiki-$MW_VERSION.tar.gz"
[ -f "$TARBALL" ] || curl -sSL --max-time 300 -o "$TARBALL" \
	"https://releases.wikimedia.org/mediawiki/$MW_SERIES/mediawiki-$MW_VERSION.tar.gz"
tar -xzf "$TARBALL" -C "$WIKI" --strip-components=1

echo "==> install"
php "$WIKI/maintenance/run.php" install \
	--dbtype=mysql --dbserver=127.0.0.1 --dbname="$DB_NAME" \
	--dbuser="$DB_USER" --dbpass="$DB_PASS" \
	--server="http://localhost:$PORT" --scriptpath="" \
	--lang=en --pass="$ADMIN_PASS" \
	"Continuity Wiki" "$ADMIN_USER" >/dev/null

# Our settings are version controlled; the installer's output just points at them.
printf '\n// Continuity overrides — see wiki-config/LocalSettings.overrides.php (version controlled).\nrequire_once __DIR__ . "/../wiki-config/LocalSettings.overrides.php";\n' \
	>> "$WIKI/LocalSettings.php"

echo "==> bot account"
# A BotPassword, not the admin's own credentials: main-account API login is deprecated and
# refused, and this one is separately revocable via invalidateBotPasswords.php.
php "$WIKI/maintenance/run.php" createAndPromote --bot --force \
	--custom-groups=bot "$BOT_NAME" "$(openssl rand -hex 16)" >/dev/null
BOT_LINE="$(php "$WIKI/maintenance/run.php" createBotPassword \
	--appid="$BOT_APPID" --grants=basic,editpage,createeditmovepage "$BOT_NAME" | tail -1)"
BOT_PASS="$(printf '%s' "$BOT_LINE" | sed -E "s/.*password:'([^']+)'.*/\1/")"
[ ${#BOT_PASS} -eq 32 ] || { echo "could not parse the bot password from: $BOT_LINE"; exit 1; }

echo "==> .env"
cat >> "$ENV_FILE" <<ENV

# --- MediaWiki (own instance; never the real Fandom wiki) ---
# Generated by scripts/setup_wiki.sh. Rotate the bot password with:
#   php wiki/maintenance/run.php invalidateBotPasswords --user $BOT_NAME
MEDIAWIKI_API_URL=http://localhost:$PORT/api.php
MEDIAWIKI_API_KEY=$API_KEY
MEDIAWIKI_DB_NAME=$DB_NAME
MEDIAWIKI_DB_USER=$DB_USER
MEDIAWIKI_DB_PASSWORD=$DB_PASS
MEDIAWIKI_ADMIN_USER=$ADMIN_USER
MEDIAWIKI_ADMIN_PASSWORD=$ADMIN_PASS
MEDIAWIKI_BOT_USER=$BOT_NAME@$BOT_APPID
MEDIAWIKI_BOT_PASSWORD=$BOT_PASS
ENV

cat <<DONE

Installed. Credentials are in .env (gitignored).

  php -S localhost:$PORT -t wiki          # serve it
  python3 scripts/seed_wiki.py --check    # confirm it matches the profile
  python3 scripts/seed_wiki.py            # load the 12 seed pages
DONE
